server.port=8080

# In production, the origin you pass in /sessions must be HTTPS.
# For local demos, you can still run on http://localhost but your platform may require HTTPS origins.

vas.host=apitest.cybersource.com
# Unified Click to Pay: backend call begins with a server-to-server call to the sessions API.
# Path can vary by tenant/product configuration. Keep it configurable.
vas.sessions.path=/uctp/v1/sessions

# Merchant authentication (HTTP Signature)
#merchant.id=meosre_clicktopay
#merchant.keyId=fb3e2ea2-7f8f-415e-93e0-a6d4233bf544
#merchant.secretKey=KiU+FwWJ/gqYI56Ewuk/pPApLtjsugWdbjHDpRpBdag=

# Ruta local a tu private key MLE en formato PEM PKCS#8.
# IMPORTANT: no se versiona. Configúralo con una ruta válida en tu máquina.
# Ejemplo macOS: /Users/tuUsuario/keys/private.pem
# Ejemplo Windows: C:/Users/tuUsuario/keys/private.pem
#ctp.mle.private-key-path=

# true solo para sandbox/dev
ctp.debug.show-decrypted=true

merchant.id=test_uctp_001
merchant.keyId=7d4af3c5-0380-4ecb-a4bc-2497473153a6
merchant.secretKey=8vIDj51zw/2W8yiAUFKhvdmJfnyYXT/ZRQ9YHU9UCCg=

logging.level.root=INFO

ctp.mle.private-key-path=/Users/jrgsolis/Projects/cybersource/uctp-sessions-buttonless-demo/src/main/resources/static/pem/private.pem
